# https://gitpod.io/#https://github.com/chimurai/jscodeshift-typescript-example
# https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - init: |
      yarn install
      yarn test
github:
  # https://www.gitpod.io/docs/prebuilds/#configure-prebuilds
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - yzhang.markdown-all-in-one
