# https://gitpod.io/#https://github.com/chimurai/jscodeshift-typescript-example
# https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - init: |
      yarn install
      yarn test --maxWorkers=30%

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - yzhang.markdown-all-in-one
