# https://gitpod.io/#https://github.com/chimurai/jscodeshift-typescript-example
# https://www.gitpod.io/docs/config-gitpod-file

tasks:
  - init: |
      npm install
      npm test run

vscode:
  extensions:
    - bierner.markdown-preview-github-styles
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - vitest.explorer
    - yzhang.markdown-all-in-one
